'use client';

import React from 'react';
import { usePageTitle } from '../components/PageTitleContext';

export default function HelpPage() {
  usePageTitle('Help & Documentation');

  return (
    <main className="flex-1 p-8 pt-24 overflow-y-auto custom-scrollbar relative space-y-12 focus:outline-none text-slate-300">
      <div className="absolute top-6 right-8 text-[9px] text-slate-800 uppercase tracking-widest select-none pointer-events-none opacity-40">
          This page is screenshot-ready for documentation.
      </div>
      <div className="max-w-3xl mx-auto space-y-12 pb-24">
        
        <section className="bg-white/[0.02] border border-white/10 rounded-[5px] p-6 shadow-lg">
          <h2 className="text-sm font-bold uppercase tracking-widest text-slate-300 mb-4 border-b border-white/10 pb-2">Intelligence Dashboard</h2>
          <p className="text-xs leading-relaxed text-slate-400">
            The Intelligence dashboard surfaces real-time telemetry, model operations, and network insights from the Mesh Maestro AI. It serves as your primary window into the cognitive layer of the Wnode network.
          </p>
        </section>

        <section className="bg-white/[0.02] border border-white/10 rounded-[5px] p-6 shadow-lg">
          <h2 className="text-sm font-bold uppercase tracking-widest text-slate-300 mb-4 border-b border-white/10 pb-2">System Insights</h2>
          <p className="text-xs leading-relaxed text-slate-400 mb-3">
            Insights are short, actionable alerts generated by the AI based on network data. Click on any insight in the left panel to open the Insight Drawer, where you can view metadata and ask contextual questions.
          </p>
          <ul className="list-disc pl-5 text-xs text-slate-400 space-y-2">
            <li><strong>Normal:</strong> Standard operational updates and general summaries.</li>
            <li><strong>Moderate:</strong> Anomalies that require attention but not immediate action.</li>
            <li><strong>Critical:</strong> Immediate action required to maintain node health.</li>
          </ul>
        </section>

        <section className="bg-white/[0.02] border border-white/10 rounded-[5px] p-6 shadow-lg">
          <h2 className="text-sm font-bold uppercase tracking-widest text-slate-300 mb-4 border-b border-white/10 pb-2">Files Indexed</h2>
          <p className="text-xs leading-relaxed text-slate-400">
            "Files Indexed" represents the number of Markdown documents stored in the local AI memory directory. The system uses these files to provide contextual awareness when answering questions.
          </p>
        </section>

        <section className="bg-white/[0.02] border border-white/10 rounded-[5px] p-6 shadow-lg">
          <h2 className="text-sm font-bold uppercase tracking-widest text-slate-300 mb-4 border-b border-white/10 pb-2">Model Integration</h2>
          <p className="text-xs leading-relaxed text-slate-400">
            The local AI model processes prompts directly on your server. It powers the conversational ChatUI and the Insight Drawer contextual chat, ensuring data privacy and speed.
          </p>
        </section>
        
        <section className="bg-white/[0.02] border border-white/10 rounded-[5px] p-6 shadow-lg">
          <h2 className="text-sm font-bold uppercase tracking-widest text-slate-300 mb-4 border-b border-white/10 pb-2">Insight Drawer Usage</h2>
          <p className="text-xs leading-relaxed text-slate-400">
            When you click an insight, the drawer slides out to provide a dedicated chat space. You can use the text box at the bottom to ask the Maestro model specific questions about that insight's root cause or implications.
          </p>
        </section>

      </div>
    </main>
  );
}
